name: Compile and deploy

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: 8.0.X # to use this version or newer ones in the future
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the code # use a featured action Checkout and copy just uses: actions/checkout@v4.2.2
        uses: actions/checkout@v4.2.2 # check out a git repository at a particular version
     # we need to install .NET.  In feature action search for Setup .NET Core SDK
     # just copy -name and uses:

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: ${{env.DOTNET_VERSION}} # to update the version dynamically based on above
          
      - name: Getting the dependencies
        run: dotnet restore # do download the packages associated with the project.  Similar/like to npm install.
        
      - name: Compile
        run: dotnet build --no-restore # because we already have a restore above
         

        
      
  
